// <auto-generated />
namespace ShadyPines.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class BDecember042014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BDecember042014));
        
        string IMigrationMetadata.Id
        {
            get { return "201412041152187_B-December-04-2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
